export class RegisterModel{
    r_name:string=''; 
    r_categories:string='';
    r_cusines:string='';
    r_services:string='';
    r_open_time:string='';
    r_close_time:string='';
    r_min_price:string='';
    r_max_price:string='';
    r_area:string='';
    r_street:string='';
    r_city:string='';
    r_pincode:string='';
    r_latitude:string='';
    r_longitude:string='';
    r_experience:string='';
    r_specials:string='';
    r_address:string='';
}