export class RegisterModel{
    "op":"";
    "m_name":""; 
    "m_categories":"";
    "m_cusines":"";
    "m_services":"";
    "m_open_time":"";
    "m_close_time":"";
    "m_min_price":"";
    "m_max_price":"";
    "m_area":"";
    "m_street":"";
    "m_city":"";
    "m_pincode":"";
    "m_latitude":"";
    "m_longitude":"";
    "m_experience":"";
    "m_specials":"";
    "m_address":"";
}